In [30]:
import numpy as np

arr = np.random.randint(1,50,(3,4))
arr

array([[36,  6, 18, 24],
       [43, 47, 39,  4],
       [25, 29, 10, 11]])

In [31]:
print(arr.mean(axis=1))
print(arr.std(axis=1))
print(arr.var(axis=1))

[21.   33.25 18.75]
[10.81665383 17.12271883  8.37779804]
[117.     293.1875  70.1875]


In [13]:
arr = np.random.randint(1,50,10)
print(arr)
print(np.sort(arr))
print(np.argsort(arr))

[44 25 19 47 36 35  5 25 30  9]
[ 5  9 19 25 25 30 35 36 44 47]
[6 9 2 1 7 8 5 4 0 3]


In [15]:
B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]
arr1 = np.array(B)
print(arr1)
print(np.sort(arr1))
print(np.argsort(arr1))
arr1[np.argsort(arr1)]

[56 48 22 41 78 91 24 46  8 33]
[ 8 22 24 33 41 46 48 56 78 91]
[8 2 6 9 3 7 1 0 4 5]


array([ 8, 22, 24, 33, 41, 46, 48, 56, 78, 91])

In [25]:
arr = np.random.randint(1,50,(3,4))
print(arr.shape)
print(type(arr))
print(arr.dtype)
arr = arr.reshape(2,6)
arr.shape

(3, 4)
<class 'numpy.ndarray'>
int32


(2, 6)